backend:
  name: github
  repo: ErwanEL/portfolio2020
  api_root: https://api.github.com
  site_domain: https://fr.erwanel.com
  base_url: https://api.netlify.com
  branch: fr-preprod

media_folder: static/assets
public_folder: /assets

collections:
  # - label: "Blog in English"
  #   name: "english_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "en"}
  #   fields:
  #     - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Content", name: "body", widget: "markdown"}
  # - label: "Blog en Español"
  #   name: "spanish_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "es"}
  #   fields:
  #     - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Titulo", name: "title", widget: "string"}
  #     - {label: "Contenido", name: "body", widget: "markdown"}
  #     - {label: "test", name: "test", widget: "markdown"}
  - label: "English Pages"
    name: "english pages"
    # media_folder: "../images/"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/contact/contact-en.yml"
        media_folder: "images"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}
          - { name: image, label: Image, widget: image }
      - label: "Form Component"
        name: "form"
        file: "site/content/pages/en/form.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
  - label: "Spanish Pages"
    name: "spanish pages"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/es/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Form Component"
        name: "form"
        file: "site/content/pages/es/form.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
  - label: "French Pages"
    name: "french pages"
    files:
      - label: "Home Page"
        name: "home"
        seo: "Home"
        file: "site/content/pages/home/home-fr.yml"
        fields:
          - {label: Dispo tag, name: dispo, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Content, name: content, widget: markdown}
          # - {label: Stacks, name: stacks, widget: list, default: ["Front-End developer", "Javascript", "GatsbyJS" ]}
          # - {label: Find me, name: findMe, widget: string}
          # - {label: Link Title, name: linkTitle, widget: string}
          # - {label: Link, name: link, widget: string}
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/contact/contact-fr.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Form Component"
        name: "form"
        file: "site/content/component/form-fr.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
      - label: "Freelance Page"
        name: "freelance"
        seo: "Freelance"
        file: "site/content/pages/freelance/freelance-fr.yml"
        media_folder: "images"
        fields:
          - {label: Seo, name: seo, widget: string}
          - {label: Emoji, name: emoji, widget: string}
          - {label: First section title, name: section0Title, widget: string}
          - {label: Second section title, name: section1Title, widget: string}
          - {label: First section content, name: section0Content, widget: string}
          - {label: Second section content, name: section1Content, widget: string}
          - {label: First section link, name: section0Link, widget: string}
          - {label: First section link title, name: section0LinkTitle, widget: string}
          - {label: Second section link, name: section1Link, widget: string}
          - {label: Second section link title, name: section1LinkTitle, widget: string}
          - { label: 'First section color', name: 'section0Color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Second section color', name: 'section1Color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: First section image, name: section0Image,  widget: image }
          - { label: Second section image, name: section1Image,  widget: image }
      - label: "Resources"
        name: "Resources"
        file: "site/content/pages/resources/resources-fr.yml"
        media_folder: "images"
        fields:
          - {label: Seo, name: seo, widget: string}
          - {label: Emoji, name: emoji, widget: string}
          - {label: First section title, name: section0Title, widget: string}
          - {label: Second section title, name: section1Title, widget: string}
          - {label: First section content, name: section0Content, widget: string}
          - {label: Second section content, name: section1Content, widget: string}
          - {label: First section link, name: section0Link, widget: string}
          - {label: First section link title, name: section0LinkTitle, widget: string}
          - {label: Second section link, name: section1Link, widget: string}
          - {label: Second section link title, name: section1LinkTitle, widget: string}
          - { label: 'First section color', name: 'section0Color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Second section color', name: 'section1Color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: First section image, name: section0Image,  widget: image }
          - { label: Second section image, name: section1Image0,  widget: image }
          - { label: Second section image 2, name: section1Image1,  widget: image }
      - label: "Skills Page"
        name: "Skills page"
        file: "site/content/pages/skills/skills-fr.yml"
        media_folder: "images"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Stacks, name: stacks, widget: list, default: ["Front-End developer", "Javascript", "GatsbyJS" ]}
          - {label: Content, name: content, widget: markdown}
          
          # - {label: Seo, name: seo, widget: string}
          # - {label: Emoji, name: emoji, widget: string}
          # - {label: First section title, name: section0Title, widget: string}
          # - {label: Second section title, name: section1Title, widget: string}
          # - {label: First section content, name: section0Content, widget: string}
          # - {label: Second section content, name: section1Content, widget: string}
          # - {label: First section link, name: section0Link, widget: string}
          # - {label: First section link title, name: section0LinkTitle, widget: string}
          # - {label: Second section link, name: section1Link, widget: string}
          # - {label: Second section link title, name: section1LinkTitle, widget: string}
          # - { label: 'First section color', name: 'section0Color', widget: 'color', enableAlpha: true, allowInput: true }
          # - { label: 'Second section color', name: 'section1Color', widget: 'color', enableAlpha: true, allowInput: true }
          # - { label: First section image, name: section0Image,  widget: image }
          # - { label: Second section image, name: section1Image0,  widget: image }
          # - { label: Second section image 2, name: section1Image1,  widget: image }

  - name: blog
    label: Blog
    folder: site/content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: code, label: Code, widget: code }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }