backend:
  name: github
  repo: ErwanEL/portfolio2020
  branch: fr-preprod

media_folder: static/assets
public_folder: /assets

collections:
  # - label: "Blog in English"
  #   name: "english_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "en"}
  #   fields:
  #     - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Content", name: "body", widget: "markdown"}
  # - label: "Blog en Español"
  #   name: "spanish_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "es"}
  #   fields:
  #     - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Titulo", name: "title", widget: "string"}
  #     - {label: "Contenido", name: "body", widget: "markdown"}
  #     - {label: "test", name: "test", widget: "markdown"}
  - label: "English Pages"
    name: "english pages"
    # media_folder: "../images/"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/contact/contact-en.yml"
        media_folder: "images"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}
          - { name: image, label: Image, widget: image }
      - label: "Form Component"
        name: "form"
        file: "site/content/pages/en/form.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
  - label: "Spanish Pages"
    name: "spanish pages"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/es/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Form Component"
        name: "form"
        file: "site/content/pages/es/form.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
  - label: "French Pages"
    name: "french pages"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/contact/contact-fr.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Form Component"
        name: "form"
        file: "site/content/component/form-fr.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
      - label: "test Page"
        name: "test"
        seo: "test"
        file: "site/content/pages/test/test-fr.yml"
        media_folder: "images"
        fields:
          - {label: Seo, name: seo, widget: string}
          - {label: section0Title, name: First section title, widget: string}
          - {label: section1Title, name: Second section title, widget: string}
          - {label: section0Content, name: First section content, widget: string}
          - {label: section1Content, name: Second section content, widget: string}
          - {label: section0Link, name: First section link, widget: string}
          - {label: section1Link, name: Second section link, widget: string}
          - { label: 'section0Color', name: 'First section color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'section1Color', name: 'Second section color', widget: 'color', enableAlpha: true, allowInput: true }
          - { name: section0Image, label: First section image, widget: image }
          - { name: section1Image, label: Second section image, widget: image }

  - name: blog
    label: Blog
    folder: site/content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: code, label: Code, widget: code }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }