backend:
  name: github
  repo: ErwanEL/portfolio2020
  api_root: https://api.github.com
  site_domain: https://erwanel.com
  base_url: https://api.netlify.com
  branch: blog-dev

media_folder: src/data/images
public_folder: /uploads

collections:
  # - label: "Blog in English"
  #   name: "english_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "en"}
  #   fields:
  #     - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Content", name: "body", widget: "markdown"}
  # - label: "Blog en Español"
  #   name: "spanish_posts"
  #   folder: "_posts"
  #   create: true
  #   filter: {field: "language", value: "es"}
  #   fields:
  #     - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
  #     - {label: "Titulo", name: "title", widget: "string"}
  #     - {label: "Contenido", name: "body", widget: "markdown"}
  #     - {label: "test", name: "test", widget: "markdown"}
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: type, label: Type }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: featuredImage, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }