backend:
  name: github
  repo: ErwanEL/portfolio2020
  branch: blog

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Contact Page"
        name: "contact"
        seo: "Contact"
        file: "site/content/pages/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Seo, name: seo, widget: string}
          - {label: Success, name: success, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Form Component"
        name: "form"
        file: "site/content/pages/form.yml"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: NamePlaceholder, name: namePlaceholder, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: EmailPlaceholder, name: emailPlaceholder, widget: string}
          - {label: Message, name: message, widget: string}
          - {label: MessagePlaceholder, name: messagePlaceholder, widget: string}
          - {label: Send, name: send, widget: string}
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: code, label: Code, widget: code }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }